/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTurmasRouteImport } from './routes/_public/turmas'
import { Route as PublicSobreRouteImport } from './routes/_public/sobre'
import { Route as PublicSimuladosRouteImport } from './routes/_public/simulados'
import { Route as PublicQuestoesRouteImport } from './routes/_public/questoes'
import { Route as PublicProvasRouteImport } from './routes/_public/provas'
import { Route as PublicFlashcardsRouteImport } from './routes/_public/flashcards'
import { Route as PublicConfiguracoesRouteImport } from './routes/_public/configuracoes'
import { Route as PublicAbordagemRouteImport } from './routes/_public/abordagem'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as PublicConteudosIndexRouteImport } from './routes/_public/conteudos/index'
import { Route as PublicConteudosConteudoIdRouteImport } from './routes/_public/conteudos/$conteudoId'
import { Route as DashboardContentCreatecontentRouteImport } from './routes/_dashboard/content/createcontent'
import { Route as DashboardContentContentsRouteImport } from './routes/_dashboard/content/contents'
import { Route as DashboardContentEditContentRouteImport } from './routes/_dashboard/content/$editContent'
import { Route as DashboardContentContentIdRouteImport } from './routes/_dashboard/content/$contentId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTurmasRoute = PublicTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSobreRoute = PublicSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSimuladosRoute = PublicSimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQuestoesRoute = PublicQuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProvasRoute = PublicProvasRouteImport.update({
  id: '/provas',
  path: '/provas',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFlashcardsRoute = PublicFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConfiguracoesRoute = PublicConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAbordagemRoute = PublicAbordagemRouteImport.update({
  id: '/abordagem',
  path: '/abordagem',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicConteudosIndexRoute = PublicConteudosIndexRouteImport.update({
  id: '/conteudos/',
  path: '/conteudos/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConteudosConteudoIdRoute =
  PublicConteudosConteudoIdRouteImport.update({
    id: '/conteudos/$conteudoId',
    path: '/conteudos/$conteudoId',
    getParentRoute: () => PublicRoute,
  } as any)
const DashboardContentCreatecontentRoute =
  DashboardContentCreatecontentRouteImport.update({
    id: '/content/createcontent',
    path: '/content/createcontent',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContentContentsRoute =
  DashboardContentContentsRouteImport.update({
    id: '/content/contents',
    path: '/content/contents',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContentEditContentRoute =
  DashboardContentEditContentRouteImport.update({
    id: '/content/$editContent',
    path: '/content/$editContent',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContentContentIdRoute =
  DashboardContentContentIdRouteImport.update({
    id: '/content/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/abordagem': typeof PublicAbordagemRoute
  '/configuracoes': typeof PublicConfiguracoesRoute
  '/flashcards': typeof PublicFlashcardsRoute
  '/provas': typeof PublicProvasRoute
  '/questoes': typeof PublicQuestoesRoute
  '/simulados': typeof PublicSimuladosRoute
  '/sobre': typeof PublicSobreRoute
  '/turmas': typeof PublicTurmasRoute
  '/': typeof PublicIndexRoute
  '/content/$contentId': typeof DashboardContentContentIdRoute
  '/content/$editContent': typeof DashboardContentEditContentRoute
  '/content/contents': typeof DashboardContentContentsRoute
  '/content/createcontent': typeof DashboardContentCreatecontentRoute
  '/conteudos/$conteudoId': typeof PublicConteudosConteudoIdRoute
  '/conteudos': typeof PublicConteudosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/abordagem': typeof PublicAbordagemRoute
  '/configuracoes': typeof PublicConfiguracoesRoute
  '/flashcards': typeof PublicFlashcardsRoute
  '/provas': typeof PublicProvasRoute
  '/questoes': typeof PublicQuestoesRoute
  '/simulados': typeof PublicSimuladosRoute
  '/sobre': typeof PublicSobreRoute
  '/turmas': typeof PublicTurmasRoute
  '/': typeof PublicIndexRoute
  '/content/$contentId': typeof DashboardContentContentIdRoute
  '/content/$editContent': typeof DashboardContentEditContentRoute
  '/content/contents': typeof DashboardContentContentsRoute
  '/content/createcontent': typeof DashboardContentCreatecontentRoute
  '/conteudos/$conteudoId': typeof PublicConteudosConteudoIdRoute
  '/conteudos': typeof PublicConteudosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_public/abordagem': typeof PublicAbordagemRoute
  '/_public/configuracoes': typeof PublicConfiguracoesRoute
  '/_public/flashcards': typeof PublicFlashcardsRoute
  '/_public/provas': typeof PublicProvasRoute
  '/_public/questoes': typeof PublicQuestoesRoute
  '/_public/simulados': typeof PublicSimuladosRoute
  '/_public/sobre': typeof PublicSobreRoute
  '/_public/turmas': typeof PublicTurmasRoute
  '/_public/': typeof PublicIndexRoute
  '/_dashboard/content/$contentId': typeof DashboardContentContentIdRoute
  '/_dashboard/content/$editContent': typeof DashboardContentEditContentRoute
  '/_dashboard/content/contents': typeof DashboardContentContentsRoute
  '/_dashboard/content/createcontent': typeof DashboardContentCreatecontentRoute
  '/_public/conteudos/$conteudoId': typeof PublicConteudosConteudoIdRoute
  '/_public/conteudos/': typeof PublicConteudosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/perfil'
    | '/dashboard'
    | '/abordagem'
    | '/configuracoes'
    | '/flashcards'
    | '/provas'
    | '/questoes'
    | '/simulados'
    | '/sobre'
    | '/turmas'
    | '/'
    | '/content/$contentId'
    | '/content/$editContent'
    | '/content/contents'
    | '/content/createcontent'
    | '/conteudos/$conteudoId'
    | '/conteudos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/perfil'
    | '/dashboard'
    | '/abordagem'
    | '/configuracoes'
    | '/flashcards'
    | '/provas'
    | '/questoes'
    | '/simulados'
    | '/sobre'
    | '/turmas'
    | '/'
    | '/content/$contentId'
    | '/content/$editContent'
    | '/content/contents'
    | '/content/createcontent'
    | '/conteudos/$conteudoId'
    | '/conteudos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_dashboard'
    | '/_public'
    | '/login'
    | '/register'
    | '/_authenticated/perfil'
    | '/_dashboard/dashboard'
    | '/_public/abordagem'
    | '/_public/configuracoes'
    | '/_public/flashcards'
    | '/_public/provas'
    | '/_public/questoes'
    | '/_public/simulados'
    | '/_public/sobre'
    | '/_public/turmas'
    | '/_public/'
    | '/_dashboard/content/$contentId'
    | '/_dashboard/content/$editContent'
    | '/_dashboard/content/contents'
    | '/_dashboard/content/createcontent'
    | '/_public/conteudos/$conteudoId'
    | '/_public/conteudos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/turmas': {
      id: '/_public/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof PublicTurmasRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sobre': {
      id: '/_public/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicSobreRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/simulados': {
      id: '/_public/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof PublicSimuladosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/questoes': {
      id: '/_public/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof PublicQuestoesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/provas': {
      id: '/_public/provas'
      path: '/provas'
      fullPath: '/provas'
      preLoaderRoute: typeof PublicProvasRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/flashcards': {
      id: '/_public/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof PublicFlashcardsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/configuracoes': {
      id: '/_public/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof PublicConfiguracoesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/abordagem': {
      id: '/_public/abordagem'
      path: '/abordagem'
      fullPath: '/abordagem'
      preLoaderRoute: typeof PublicAbordagemRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/conteudos/': {
      id: '/_public/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof PublicConteudosIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/conteudos/$conteudoId': {
      id: '/_public/conteudos/$conteudoId'
      path: '/conteudos/$conteudoId'
      fullPath: '/conteudos/$conteudoId'
      preLoaderRoute: typeof PublicConteudosConteudoIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_dashboard/content/createcontent': {
      id: '/_dashboard/content/createcontent'
      path: '/content/createcontent'
      fullPath: '/content/createcontent'
      preLoaderRoute: typeof DashboardContentCreatecontentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/contents': {
      id: '/_dashboard/content/contents'
      path: '/content/contents'
      fullPath: '/content/contents'
      preLoaderRoute: typeof DashboardContentContentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/$editContent': {
      id: '/_dashboard/content/$editContent'
      path: '/content/$editContent'
      fullPath: '/content/$editContent'
      preLoaderRoute: typeof DashboardContentEditContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/$contentId': {
      id: '/_dashboard/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof DashboardContentContentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardContentContentIdRoute: typeof DashboardContentContentIdRoute
  DashboardContentEditContentRoute: typeof DashboardContentEditContentRoute
  DashboardContentContentsRoute: typeof DashboardContentContentsRoute
  DashboardContentCreatecontentRoute: typeof DashboardContentCreatecontentRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardContentContentIdRoute: DashboardContentContentIdRoute,
  DashboardContentEditContentRoute: DashboardContentEditContentRoute,
  DashboardContentContentsRoute: DashboardContentContentsRoute,
  DashboardContentCreatecontentRoute: DashboardContentCreatecontentRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PublicRouteChildren {
  PublicAbordagemRoute: typeof PublicAbordagemRoute
  PublicConfiguracoesRoute: typeof PublicConfiguracoesRoute
  PublicFlashcardsRoute: typeof PublicFlashcardsRoute
  PublicProvasRoute: typeof PublicProvasRoute
  PublicQuestoesRoute: typeof PublicQuestoesRoute
  PublicSimuladosRoute: typeof PublicSimuladosRoute
  PublicSobreRoute: typeof PublicSobreRoute
  PublicTurmasRoute: typeof PublicTurmasRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicConteudosConteudoIdRoute: typeof PublicConteudosConteudoIdRoute
  PublicConteudosIndexRoute: typeof PublicConteudosIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAbordagemRoute: PublicAbordagemRoute,
  PublicConfiguracoesRoute: PublicConfiguracoesRoute,
  PublicFlashcardsRoute: PublicFlashcardsRoute,
  PublicProvasRoute: PublicProvasRoute,
  PublicQuestoesRoute: PublicQuestoesRoute,
  PublicSimuladosRoute: PublicSimuladosRoute,
  PublicSobreRoute: PublicSobreRoute,
  PublicTurmasRoute: PublicTurmasRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicConteudosConteudoIdRoute: PublicConteudosConteudoIdRoute,
  PublicConteudosIndexRoute: PublicConteudosIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
