name: Run Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  vitest:
    name: Run Vitest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Vitest tests
        run: npm run test

  cypress:
    name: Run Cypress Tests on Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Start Storybook
        run: npm run storybook &
        env:
          NODE_ENV: test

      - name: Wait for Storybook to be ready
        run: npx wait-on http://localhost:6006

      - name: Run Cypress tests
        run: npx cypress run